name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: anomaly-reaper
  REGION: ${{ secrets.GCP_REGION }}
  REPOSITORY: anomaly-reaper # Artifact Registry repository name

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      # Configure Workload Identity Federation and generate access token
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2' # Updated to v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      # Set up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2' # Updated to v2

      # Set up Docker Buildx for efficient builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Setup Docker Layer Caching
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Configure Docker to use gcloud as a credential helper
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # Extract short SHA for tagging
      - name: Extract Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Generate version tag based on git history
      - name: Generate Version
        run: |
          VERSION=$(git describe --tags --always --dirty || echo $(date +%Y%m%d)-$(git rev-parse --short HEAD))
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build and push the Docker image to Google Artifact Registry
      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}

      # Move cache to prevent cache bloat
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Scan container for vulnerabilities
      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'

      # Set up image name for deployment
      - name: Set Image Name
        run: echo "IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      # Deploy to Cloud Run with improved settings
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_NAME }}
          flags: |
            --allow-unauthenticated
            --port=8000
            --cpu=1
            --memory=1Gi
            --min-instances=0
            --max-instances=10
            --concurrency=80
            --timeout=300s
          env_vars: |
            PYTHON_ENV=production
            GCP_PROJECT=${{ env.PROJECT_ID }}
          secrets: |
            DATABASE_URL=DATABASE_URL:latest

      # Output the deployed service URL
      - name: Show Service URL
        run: echo "Service URL ${{ steps.deploy.outputs.url }}"
      
      # Improved health check with retries
      - name: Health Check
        id: health-check
        run: |
          SERVICE_URL="${{ steps.deploy.outputs.url }}"
          HEALTH_ENDPOINT="/health"
          MAX_RETRIES=10
          RETRY_INTERVAL=15
          
          echo "Performing health check on ${SERVICE_URL}${HEALTH_ENDPOINT}"
          
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i of $MAX_RETRIES..."
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "${SERVICE_URL}${HEALTH_ENDPOINT}")
            
            if [ "$RESPONSE" -eq 200 ]; then
              echo "Health check passed with HTTP 200"
              exit 0
            else
              echo "Health check returned HTTP ${RESPONSE}, retrying in ${RETRY_INTERVAL} seconds..."
              sleep $RETRY_INTERVAL
            fi
          done
          
          echo "Health check failed after $MAX_RETRIES attempts"
          exit 1
