name: Development Preview Deployment

on:
  push:
    branches:
      - develop # Assuming you use a develop branch
  workflow_dispatch: # Allow manual triggering

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: anomaly-reaper-dev
  REGION: ${{ secrets.GCP_REGION }}
  DOCKER_REPO: brainwave
  
jobs:
  build-and-deploy-preview:
    name: Build and Deploy Preview
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # Set up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Build and push the Docker image
      - name: Build and Push Container
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          
          DOCKER_REPOSITORY="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}"
          IMAGE_NAME="${DOCKER_REPOSITORY}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          
          docker build -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"
          
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      # Deploy to Cloud Run (development environment)
      - name: Deploy to Cloud Run (Dev)
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_NAME }}
          flags: '--allow-unauthenticated --set-env-vars=ENVIRONMENT=develop --service-account=${{ secrets.CLOUDRUN_SERVICE_ACCOUNT }}'

      # Output the development URL
      - name: Show Development URL
        run: echo "Development Preview URL ${{ steps.deploy.outputs.url }}"
      
      # Health Check
      - name: Health Check
        id: health-check
        run: |
          sleep 30
          SERVICE_URL="${{ steps.deploy.outputs.url }}"
          echo "Performing health check on ${SERVICE_URL}/health"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "${SERVICE_URL}/health")
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Health check passed with HTTP 200"
            exit 0
          else
            echo "Health check failed with HTTP ${RESPONSE}"
            exit 1
          fi
